# Generated by Django 4.2.4 on 2023-08-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_alter_pedido_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ArquivoAnexo',
        ),
    ]
